config/routes.rb
Multidelivery::Application.routes.draw do
  resources :items

  resources :produtos

  resources :categories

  resources :empresas

  get "home/index"

  root :to => "home#index"

  resources :pedidos

  resources :clientes

end

app/models/categorias.rb
class Categorias < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :produto
  belongs_to :pedido
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :category
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
def build_resource_params
        [params.fetch(:cliente, {}).permit(:nome, :endereco, :cpf, :telefone, :celular, :email)]
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:empresa, {}).permit(:nome, :cnpj)]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:item, {}).permit(:quantidade, :produto_id, :pedido_id)]
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:pedido, {}).permit(:data, :hora, :cliente_id)]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/clientes/_form.html.haml
= semantic_form_for [@cliente] do |form|
  
  = form.input :nome, :label => 'Nome'
  = form.input :endereco, :label => 'Endereço'
  = form.input :cpf, :label => 'CPF'
  = form.input :telefone, :label => 'Telefone'
  = form.input :celular, :label => 'Celular' 
  = form.input :email, :label => 'Email'
  = form.submit 'Salvar'

app/views/clientes/edit.html.erb
<h1>Editando Cliente</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listando Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.celular %></td>
        <td><%= cliente.email %></td>
        <td><%= link_to 'Exibir', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @cliente.endereco %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>

app/views/empresas/_form.html.haml
= semantic_form_for [@empresa] do |form|
  
  = form.input :nome, :label => 'Nome'
  = form.input :cnpj, :label => 'CNPJ'
  = form.submit 'Salvar'

app/views/empresas/edit.html.erb
<h1>Editando Empresa</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @empresa %> |
<%= link_to 'Voltar', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listando Empresas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>CNPJ</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nome %></td>
        <td><%= empresa.cnpj %></td>
        <td><%= link_to 'Exibir', empresa %></td>
        <td><%= link_to 'Editar', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Excluir', empresa, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>CNPJ:</strong>
  <%= @empresa.cnpj %>
</p>

<%= link_to 'Editar', edit_empresa_path(@empresa) %> |
<%= link_to 'Voltar', empresas_path %>

app/views/items/_form.html.haml
= semantic_form_for [@item] do |form|
  
  = form.input :quantidade, :label => 'Quantidade'
  = form.input :produto, :member_label => :nome, :label => 'Produto'
  = form.input :pedido, :member_label => Proc.new { |p| h(p.cliente.nome + " " + p.data + " " + p.hora) } , :label => 'Pedido' 
  = form.submit 'Salvar'

app/views/items/edit.html.erb
<h1>Editando Item</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @item %> |
<%= link_to 'Voltar', items_path %>

app/views/items/index.html.erb
<h1>Listando Itens</h1>

<table>
  <thead>
    <tr>
      <th>Quantidade</th>
      <th>Produto</th>
      <th>Pedido</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.quantidade %></td>
        <td><%= item.produto.nome %></td>
        <td><%= item.pedido.cliente.nome %>, <%= item.pedido.data %>, <%= item.pedido.hora %></td>
        <td><%= link_to 'Exibir', item %></td>
        <td><%= link_to 'Editar', edit_item_path(item) %></td>
        <td><%= link_to 'Excluir', item, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Item', new_item_path %>

app/views/items/new.html.erb
<h1>Novo Item</h1>

<%= render 'form' %>

<%= link_to 'Voltar', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantidade:</strong>
  <%= @item.quantidade %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @item.produto.nome %>
</p>

<p>
  <strong>Pedido:</strong>
  <%= @item.pedido.cliente.nome %>
  <%= @item.pedido.data %>
  <%= @item.pedido.hora %>
</p>

<%= link_to 'Editar', edit_item_path(@item) %> |
<%= link_to 'Voltar', items_path %>

app/views/pedidos/_form.html.haml
= semantic_form_for [@pedido] do |form|
  
  = form.input :data, :label => 'Data'
  = form.input :hora, :label => 'Hora' 
  = form.input :cliente, :member_label => :nome, :label => 'Cliente' 
  = form.submit 'Salvar'

app/views/pedidos/edit.html.erb
<h1>Editando Pedido</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @pedido %> |
<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listando Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Hora</th>
      <th>Cliente</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.data %></td>
        <td><%= pedido.hora %></td>
        <td><%= pedido.cliente.nome %></td>
        <td><%= link_to 'Exibir', pedido %></td>
        <td><%= link_to 'Editar', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Excluir', pedido, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>Novo Pedido</h1>

<%= render 'form' %>

<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @pedido.data %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @pedido.hora %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @pedido.cliente.nome %>
</p>

<%= link_to 'Editar', edit_pedido_path(@pedido) %> |
<%= link_to 'Voltar', pedidos_path %>