config/routes.rb
Multidelivery::Application.routes.draw do
  resources :items

  resources :produtos

  resources :categories

  resources :empresas

  get "home/index"

  root :to => "home#index"

  resources :pedidos

  resources :clientes

end

app/models/categorias.rb
class Categorias < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :produto
  belongs_to :pedido
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :category
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
def build_resource_params
        [params.fetch(:cliente, {}).permit(:nome, :endereco, :cpf, :telefone, :celular, :email)]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:item, {}).permit(:quantidade, :produto_id, :pedido_id)]
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:pedido, {}).permit(:data, :hora, :cliente_id)]
    end

end

app/controllers/produtos_controller.rb
class ProdutosController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:produto, {}).permit(:nome, :peso, :empresa_id, :category_id)]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.text_field :peso %>
  </div>
  <div class="field">
    <%= f.label :empresa_id %><br>
    <%= f.text_field :empresa_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/_form.html.haml
= semantic_form_for [@produto] do |form|
  
  = form.input :nome, :label => 'Nome'
  = form.input :peso, :label => 'Peso' 
  = form.input :empresa, :member_label => :nome, :label => 'Empresa' 
  = form.input :category, :member_label => :nome, :label => 'Category' 
  = form.submit 'Salvar'

app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listando Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Peso</th>
      <th>Empresa</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.peso %></td>
        <td><%= produto.empresa.nome %></td>
        <td><%= produto.category.nome %></td>
        <td><%= link_to 'Exibir', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @produto.peso %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @produto.empresa.nome %>
</p>

<p>
  <strong>Category:</strong>
  <%= @produto.category.nome %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>