config/routes.rb
Multidelivery::Application.routes.draw do
  resources :items

  resources :produtos

  resources :categories

  resources :empresas

  get "home/index"

  root :to => "home#index"

  resources :pedidos

  resources :clientes

end

app/models/categorias.rb
class Categorias < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :produto
  belongs_to :pedido
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :category
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

    def build_resource_params
        [params.fetch(:item, {}).permit(:quantidade, :produto_id, :pedido_id)]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : CrossWalk 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20140216

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Multidelivery</title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :application %>
<%= csrf_meta_tag %>
<%= favicon_link_tag 'favicon.jpg' %>

<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>
<body>
<div id="wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1>Multidelivery</h1>
		</div>
		<div id="menu">
			<ul class="menuprincipal">
                <li><a href="/" accesskey="1" title="">Homepage</a></li>
				<li> <%= link_to 'Empresa',empresas_path %> </li>
				<li> <%= link_to 'Categoria',categories_path %></li>
                <li> <%= link_to 'Produto',produtos_path %></li>
                <li> <%= link_to 'Cliente',clientes_path %></li>
				<li> <%= link_to 'Pedido',pedidos_path %></li>
				<li> <%= link_to 'Item Pedido',items_path %></li>
			</ul>
		</div>
	</div>
	<div id="banner">
    <%= image_tag "logohorizontal.png", {height: 150} %>
    </div>
	<div id="featured">
		<%= yield %>
	</div>

</body>
</html>